### ISSUE TITLE
Streaming seems to break with large responses

### ISSUE THREAD

**Issue by jmontleon** [opendatahub-io/caikit-nlp-client#95]
I've been serving `codellama/CodeLlama-7b-hf` using openshift AI `Caikit TGIS ServingRuntime for KServe` and trying to interact with it using langchain via `caikit-nlp-client` and [caikit_tgis_langchain.py](https://github.com/rh-aiservices-bu/llm-on-openshift/blob/main/examples/notebooks/langchain/caikit_tgis_langchain.py), although I had to edit it to get it to even load. (Separate issue here: https://github.com/rh-aiservices-bu/llm-on-openshift/issues/32)

It seems like with large responses it will stream for awhile and then things will hang up and I'll get a huge block of text that won't decode properly because there's a date time stamp, that looks like ` - 2024-01-19 16:43:27.101423` ahead of the block of json; not to mention it seems like multiple json objects ({ "generated_text": .... }{ "generated_text": ... }) not constructed in an array with brackets or comma separated.

I have modified the serving runtime to add some env vars and command line options, tolerations, etc. 
```
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: "true"
metadata:
  annotations:
    openshift.io/display-name: Caikit TGIS ServingRuntime for KServe with increased tokens
  name: caikit-tgis-runtime-copy
spec:
  containers:
    - args:
        - --model-name=/mnt/models/artifacts/
        - --max-sequence-length=16384
        - --max-new-tokens=16384
        - --max-prefill-weight=9000000
      command:
        - text-generation-launcher
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
        - name: PYTORCH_CUDA_ALLOC_CONF
          value: garbage_collection_threshold:0.5,max_split_size_mb:128M
      image: quay.io/opendatahub/text-generation-inference@sha256:efcc60c671a5da62c0251bc543f6de73f6578aac40a9a745eae3f60b0208f9e9
      name: kserve-container
    - env:
        - name: RUNTIME_LOCAL_MODELS_DIR
          value: /mnt/models
        - name: RUNTIME_GRPC_SERVER_THREAD_POOL_SIZE
          value: "2"
        - name: PYTORCH_CUDA_ALLOC_CONF
          value: garbage_collection_threshold:0.5,max_split_size_mb:128M
      image: quay.io/opendatahub/caikit-tgis-serving@sha256:9d6e8bc10f3b61774f9d321790f8593f6ded5674b64a366248fcde6a07d66833
      name: transformer-container
      ports:
        - containerPort: 8080
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: caikit
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
```

The example I am running is trying to reproduce some notebooks we have in https://github.com/jwmatthews/kyma_poc running against chatgpt. I am running these in an OpenShift AI Minimal Jupyter Notebook. 

To install deps with this repo to work with the notbook below you can just:
```
pip install -r requirements.txt
pip install caikit-nlp-client
```

I then add the notebook and  modified `caikit_tgis_langchain.py` (the txt extensions for GitHub's sake and should be removed).
[caikit_tgis_langchain.py.txt](https://github.com/opendatahub-io/caikit-nlp-client/files/13991760/caikit_tgis_langchain.py.txt)
[OpenShift-AI-API-Test.ipynb.txt](https://github.com/opendatahub-io/caikit-nlp-client/files/13991745/OpenShift-AI-API-Test.ipynb.txt)

When I run this I start to get output streaming, but it abruptly stops. If I wait a bit I'll get error output coming from `http_client.py`: `--> 268     final_message = json.loads(b"".join(buffer))`
```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
Cell In[1], line 258
    249 #prompt="Write a hello world program in python"
    252 llm = caikit_tgis_langchain.CaikitLLM(
    253     inference_server_url="https://codellama-7b-hf-predictor-kyma-workshop.apps.ai.migration.redhat.com/",
    254     model_id="CodeLlama-7b-hf",
    255     streaming=True
    256 )
--> 258 for chunk in llm.stream(prompt, max_new_tokens=4096):
    259     print(chunk, end="", flush=True)

File /opt/app-root/lib64/python3.9/site-packages/langchain/llms/base.py:396, in BaseLLM.stream(self, input, config, stop, **kwargs)
    394 except BaseException as e:
    395     run_manager.on_llm_error(e)
--> 396     raise e
    397 else:
    398     run_manager.on_llm_end(LLMResult(generations=[[generation]]))

File /opt/app-root/lib64/python3.9/site-packages/langchain/llms/base.py:385, in BaseLLM.stream(self, input, config, stop, **kwargs)
    383 try:
    384     generation: Optional[GenerationChunk] = None
--> 385     for chunk in self._stream(
    386         prompt, stop=stop, run_manager=run_manager, **kwargs
    387     ):
    388         yield chunk.text
    389         if generation is None:

File ~/kyma_poc/nbs/caikit_tgis_langchain.py:111, in CaikitLLM._stream(self, prompt, preserve_input_text, max_new_tokens, min_new_tokens, device, stop, run_manager, **kwargs)
    108 if device or stop:
    109     raise NotImplementedError
--> 111 for token in self.client.generate_text_stream(
    112     self.model_id,
    113     prompt,
    114     preserve_input_text=preserve_input_text,
    115     max_new_tokens=max_new_tokens,
    116     min_new_tokens=min_new_tokens,
    117 ):
    118     chunk = GenerationChunk(text=token)
    119     yield chunk

File /opt/app-root/lib64/python3.9/site-packages/caikit_nlp_client/http_client.py:268, in HttpClient.generate_text_stream(self, model_id, text, timeout, **kwargs)
    265     yield message["generated_text"]
    267 if buffer:
--> 268     final_message = json.loads(b"".join(buffer))
    269     if "details" in final_message and "code" in final_message:
    270         raise RuntimeError(
    271             "Exception iterating responses: {}".format(final_message["details"])
    272         )

File /usr/lib64/python3.9/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    341     s = s.decode(detect_encoding(s), 'surrogatepass')
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:
    348     cls = JSONDecoder

File /usr/lib64/python3.9/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    332 def decode(self, s, _w=WHITESPACE.match):
    333     """Return the Python representation of ``s`` (a ``str`` instance
    334     containing a JSON document).
    335 
    336     """
--> 337     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338     end = _w(s, end).end()
    339     if end != len(s):

File /usr/lib64/python3.9/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

Adding a print above this yields more json responses, but they're not properly formatted.
They start with a date/time string ` - 2024-01-19 16:43:27.101423`. They're also like a badly formatted array without brackets, and commas separating them. Additional date/times will be included in between every few hundred items. I've included just a snippet of text to give an idea as it's extremely long.

```
 - 2024-01-19 16:43:27.101423{  "generated_text": ";",  "tokens": [    {      "text": "<0x0A>",      "logprob": -0.00029952809563837945    }  ],  "details": {    "finish_reason": "NOT_FINISHED",    "generated_tokens": 325,    "seed": 0,    "input_token_count": 0  },  "producer_id": null}{  "generated_text": "\n              ",  "tokens": [    {      "text": "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",      "logprob": -0.005214542616158724    }  ],  "details": {    "finish_reason": "NOT_FINISHED",    "generated_tokens": 326,    "seed": 0,    "input_token_count": 0  },  "producer_id": null}{  "generated_text": "  i",  "tokens": [    {      "text": "▁if",      "logprob": -0.0022460015024989843    }  ],  "details": {    "finish_reason": "NOT_FINISHED",    "generated_tokens": 327,    "seed": 0,    "input_token_count": 0  },  "producer_id": null}{  "generated_text": "f ",  "tokens": [    {      "text": "▁(",      "logprob": -0.00013100242358632386    }  ],  "details": {    "finish_reason": "NOT_FINISHED",    "generated_tokens": 328,    "seed": 0,    "input_token_count": 0  },  "producer_id": null}{  "generated_text": "(r",  "tokens": [ ......
```

If I do some crude handling of the unexpected output I can at least get a wall of text if I wait after it stops streaming:
```
diff --git a/home/jason/Documents/src/github.com/opendatahub-io/caikit-nlp-client/src/caikit_nlp_client/http_client.py b/http_client.py
index e21271a..10f8106 100644
--- a/home/jason/Documents/src/github.com/opendatahub-io/caikit-nlp-client/src/caikit_nlp_client/http_client.py
+++ b/http_client.py
@@ -265,13 +265,23 @@ class HttpClient:
             yield message["generated_text"]
 
         if buffer:
-            final_message = json.loads(b"".join(buffer))
+            import re
+            pattern = re.compile(' - [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]')
+            txt = b"".join(buffer).decode()
+            txt = re.sub(pattern, '', txt)
+            txt = re.sub('}{', '},{', txt)
+            txt = '[' + txt + ']'
+            #print(txt)
+            final_message = json.loads(txt.encode('utf-8'))
             if "details" in final_message and "code" in final_message:
                 raise RuntimeError(
                     "Exception iterating responses: {}".format(final_message["details"])
                 )
             try:
-                yield final_message["generated_text"]
+                final_message_string = ""
+                for i in final_message:
+                    final_message_string += i["generated_text"]
+                yield final_message_string
             except KeyError as exc:
                 raise RuntimeError(
                     "Unexpected response from the server: generated text is missing"
```
